"""Stereographic polar-cap NHQG solver components."""

from sphere_nhqg.geometry import (
    azimuthal_arc_length_factor,
    cap_area_fraction_from_latitude,
    cap_radius_from_colatitude,
    cap_radius_from_latitude,
    conformal_factor,
    coriolis_parameter,
    exact_cap_area,
    inverse_conformal_factor,
    latitude_from_radius,
    radial_arc_length_factor,
    radial_coriolis_gradient,
    spherical_area_density,
    stereographic_colatitude_from_radius,
)
from sphere_nhqg.mean_exchange import (
    spherical_area_mean_axisymmetric,
    spherical_area_mean_weights,
)
from sphere_nhqg.operators import (
    flat_laplacian_matrix,
    helmholtz_matrix,
    helmholtz_rhs,
    solve_helmholtz,
    spherical_laplacian_matrix,
)
from sphere_nhqg.radial import (
    RadialBasis,
    basis_values_at_r,
    coefficients_to_physical,
    derivative_values_at_r,
    flat_inner_product_from_coefficients,
    jacobi_norms,
    make_radial_basis,
    physical_to_coefficients,
    polynomial_to_coefficients,
    radial_derivative_from_coefficients,
    radial_derivative_from_physical,
)
from sphere_nhqg.spectral import (
    SpectralGrid,
    azimuthal_derivative_to_physical,
    constant_coefficients,
    coefficients_to_physical as spectral_coefficients_to_physical,
    dealiased_product,
    flat_jacobian_coefficients,
    flat_jacobian_physical,
    make_spectral_grid,
    physical_to_coefficients as spectral_physical_to_coefficients,
    radial_derivative_to_physical,
    spherical_jacobian_coefficients,
    spherical_jacobian_physical,
)

__all__ = [
    "RadialBasis",
    "SpectralGrid",
    "azimuthal_arc_length_factor",
    "azimuthal_derivative_to_physical",
    "basis_values_at_r",
    "cap_area_fraction_from_latitude",
    "cap_radius_from_colatitude",
    "cap_radius_from_latitude",
    "coefficients_to_physical",
    "conformal_factor",
    "constant_coefficients",
    "coriolis_parameter",
    "dealiased_product",
    "derivative_values_at_r",
    "exact_cap_area",
    "flat_laplacian_matrix",
    "flat_inner_product_from_coefficients",
    "flat_jacobian_coefficients",
    "flat_jacobian_physical",
    "helmholtz_matrix",
    "helmholtz_rhs",
    "inverse_conformal_factor",
    "jacobi_norms",
    "latitude_from_radius",
    "make_radial_basis",
    "make_spectral_grid",
    "physical_to_coefficients",
    "polynomial_to_coefficients",
    "radial_arc_length_factor",
    "radial_coriolis_gradient",
    "radial_derivative_from_coefficients",
    "radial_derivative_from_physical",
    "radial_derivative_to_physical",
    "solve_helmholtz",
    "spherical_area_mean_axisymmetric",
    "spherical_area_mean_weights",
    "spherical_jacobian_coefficients",
    "spherical_jacobian_physical",
    "spherical_laplacian_matrix",
    "spherical_area_density",
    "spectral_coefficients_to_physical",
    "spectral_physical_to_coefficients",
    "stereographic_colatitude_from_radius",
]
